### PR TITLE
Add onKeyDown in ITreeViewProps

### PR DESCRIPTION
**Pull request by alexandrudanpop**
https://github.com/dgreene1/react-accessible-treeview/issues/202

### CODE REVIEW

**Comment by dgreene1** [comment]
@mellis481, do you have any objections to this? It could be a “foot gun” if people use it to do things that invalidate accessibility, but that would be on them. Doesn’t harm people if they don’t use it. Thoughts?

Could we insulate ourselves from maintenance problems and say in the JsDoc for this property “this prop is unsupported so please do not make issues in the github repo about it.”

**Comment by mellis481** [comment]
@dgreene1 @alexandrudanpop Upon a cursory review, it looks like it would completely break this component as it would override what appears to be the most critical piece of functionality in the tree. https://github.com/dgreene1/react-accessible-treeview/blob/b6ff1eb9fef901b4e21ee9300f1a323568a3ec66/src/TreeView/index.tsx#L633-L647

One _could_ add it to the current onKeyDown call which I'm not sure why the author did not.

**Comment by alexandrudanpop** [comment]
> @dgreene1 @alexandrudanpop Upon a cursory review, it looks like it would completely break this component as it would override what appears to be the most critical piece of functionality in the tree.
> 
> https://github.com/dgreene1/react-accessible-treeview/blob/b6ff1eb9fef901b4e21ee9300f1a323568a3ec66/src/TreeView/index.tsx#L633-L647
> 
> One _could_ add it to the current onKeyDown call which I'm not sure why the author did not.

In our usecase I want to disable the keyboard navigations for two reasons:
- the highlight when you navigate with the keyboard from parent to leaf nodes does not work well with a custom highlight we implemented (any time something is selected it also highlights the children of the node)
- I didn't manage to quickly make the selection with keyboard work when the node has children -> `onKeyDown` was not triggered (for our use case the selection needs to trigger some custom behavior in the app, outside the component, so having this functionality work only for leaf nodes was not acceptable).

Passing a custom `onKeyDown` event also worked (just not for TS users) -> https://github.com/dgreene1/react-accessible-treeview/issues/144#issuecomment-1672895155 
Another option would be to provide a prop `disableKeyboardNavigation` that disables internally?

**Comment by dgreene1** [comment]
I’m inclined to say that if you’d like those customizations then you should fork this repo.

**Comment by mellis481** [comment]
@dgreene1 +1. The first item seems to be solved with some basic custom CSS. I can't understand what is being described in the second item, but I don't see why we would ever allow for keyboard interaction to be disabled in a library whose name includes the word "accessible".

**Comment by alexandrudanpop** [comment]
Then I guess I can close this PR, the idea was not to permanently disable the kb navigation, just to have it as an option until some app specific functional aspects are resolved. Thanks for the support & for working on this library!

**Pull request closed without merging**
