### PR TITLE
Switch PR GitHub workflow node version to LTS (v16.17.1)

### PR DESCRIPTION
**Pull request by yhy-1**

### CODE REVIEW

**Review by dgreene1 — APPROVED** [review]

**Comment by dgreene1** [comment]
@yhy-1 I can’t remember how you and your team were tracking this work. I’d recommend bringing it into your next sprint as 3 points and then resolve the issues that are occurring in CICD. When you do that, I bet you’ll end up resolving many of the dependabot issues- and if you don't please run npm audit fix. So please close those PRs too.

cc @mellis481

**Comment by dgreene1** [comment]
@yhy-1 can you remind me what’s up with this story?

**Comment by yhy-1** [comment]
There is a couple of dependencies we need to update but looks like it has been resolved in one of the PR. We can merge this now it. @dgreene1

**Comment by yhy-1** [comment]
@dgreene1 https://github.com/dgreene1/react-accessible-treeview/pull/69 resolved in this ticket.

**Pull request closed without merging**
