### PR TITLE
Updated peerDependencies to support React 18

### PR DESCRIPTION
**Pull request by Ke1sy**
Updated peerDependencies to support React 18

### CODE REVIEW

**Comment by Ke1sy** [comment]
@dgreene1 @mellis481 @yhy-1 could you please review my PR and run the workflows (UIEN-2779)? Thanks!

**Comment by mellis481** [comment]
@Ke1sy Why aren't you updating the react dependency version in this effort?

**Comment by SpaNb4** [comment]
@Ke1sy Please check the tests
image

**Comment by Ke1sy** [comment]
> @Ke1sy Please check the tests image

fixed it

**Review by mellis481 — APPROVED** [review]

**Pull request merged**
